services:
  ultravidz-public:
    container_name: ultravidz-public
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ultravidz-public-secure.entrypoints=https"
      - "traefik.http.routers.ultravidz-public-secure.rule=Host(`ultravidz.com`)"
      - "traefik.http.routers.ultravidz-public-secure.middlewares=error-pages-middleware"
      - "traefik.http.routers.ultravidz-public-secure.tls=true"
    healthcheck:
      disable: true
networks:
  proxy:
    external: true
